spring:
  application:
    name: jwt-auth demo
  datasource:
    url: jdbc:postgresql://localhost:5432/todos
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true